# Generated by Django 2.2.6 on 2022-02-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название команды', max_length=100)),
                ('external_code', models.CharField(help_text='Код из 1С', max_length=9)),
                ('pin', models.CharField(help_text='Пин-код', max_length=4)),
                ('logo', models.ImageField(help_text='Лого команды', upload_to='')),
            ],
        ),
    ]
