# Generated by Django 2.2.6 on 2022-02-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, help_text='Лого команды', upload_to=''),
        ),
    ]
