# Generated by Django 2.2.6 on 2022-02-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond',
            name='address',
            field=models.TextField(blank=True, help_text='Адрес'),
        ),
    ]
