# Generated by Django 2.2.6 on 2022-02-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0002_auto_20220209_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond',
            name='logo',
            field=models.ImageField(blank=True, help_text='Логотип водоема', upload_to=''),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер сектора')),
                ('pond', models.ForeignKey(help_text='Водоем', on_delete=django.db.models.deletion.CASCADE, to='ponds.Pond')),
            ],
        ),
    ]
