# Generated by Django 2.2.6 on 2022-02-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0003_auto_20220209_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='pond',
            field=models.ForeignKey(help_text='Водоем', on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='ponds.Pond'),
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together={('pond', 'number')},
        ),
    ]
