# Generated by Django 3.2 on 2022-02-10 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Фамилия', max_length=100)),
                ('first_name', models.CharField(help_text='Имя', max_length=100)),
                ('patronymic', models.CharField(blank=True, help_text='Отчество', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Фотография', upload_to='')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона', max_length=11)),
                ('pin', models.CharField(blank=True, help_text='Пин-код', max_length=4)),
                ('is_test', models.BooleanField(default=False, help_text='Тестовый участник')),
                ('user', models.OneToOneField(blank=True, help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
