# Generated by Django 3.2 on 2022-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Фамилия', max_length=100)),
                ('first_name', models.CharField(help_text='Имя', max_length=100)),
                ('patronymic', models.CharField(blank=True, help_text='Отчество', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Фотография', upload_to='')),
                ('url_facebook', models.URLField(blank=True, help_text='Страница Facebook')),
                ('url_instagram', models.URLField(blank=True, help_text='Страница Instagram')),
                ('url_vk', models.URLField(blank=True, help_text='Страница VK')),
                ('url_youtube', models.URLField(blank=True, help_text='Страница YouTube')),
                ('scan_id', models.FileField(blank=True, help_text='Скан паспорта', upload_to='')),
                ('health_insurance_id', models.FileField(blank=True, help_text='Скан медициской страховки', upload_to='')),
                ('sport_insurance_id', models.FileField(blank=True, help_text='Скан спортивной страховки', upload_to='')),
                ('external_code', models.CharField(help_text='Код из 1С', max_length=9)),
            ],
        ),
    ]
